apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-deployer
rules:
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - create
      - update
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - '*'