apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy-node-app
  namespace: node-app-namespace
subjects:
  - kind: ServiceAccount
    name: node-deployer-account
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-deployer