{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "example.serviceAccountName" . }}
  namespace: {{ .Values.nodeApp.namespace }}
  labels:
    {{- include "example.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  {{- end }}
{{- end }}
